### ISSUE TITLE
Issue compared to original stringy

### ISSUE THREAD

**Issue by GrahamCampbell** [voku/portable-ascii#1]
I've replaced (locally) Laravel's Str::ascii with a call to this package, however some of the results are not quite as expected. For example, the following test fails:

```php
$this->assertSame('h H sht SHT a A y Y', Str::ascii('х Х щ Щ ъ Ъ ь Ь', 'bg'));
```

```diff
Failed asserting that two strings are identical.

--- Expected
+++ Actual
@@ @@
-'h H sht SHT a A y Y'
+'h H sht Sht a A  '
```

**Comment by voku** [comment]
"ь Ь" -> In the modern Slavic Cyrillic writing systems (all East Slavic languages and Bulgarian and Church Slavic), it does not represent an individual sound but indicates palatalization of the preceding consonant. - https://en.wikipedia.org/wiki/Soft_sign

**Comment by GrahamCampbell** [comment]
Right. I wonder if the author of that test in Laravel was a native speaker? I really don't know.

**Comment by voku** [comment]
"'ь' on it's own does not make sense." - https://twitter.com/bgphp/status/1170729177139601410

**Comment by GrahamCampbell** [comment]
Right, so Laravel's tests are wrong. ;)
