### ISSUE TITLE
Deprecated: voku\helper\ASCII::to_ascii(): Implicitly marking parameter $replace_single_chars_only as nullable is deprecated, the explicit nullable type must be used instead in /Users/zx-studio/Herd/zx-studioweb/vendor/voku/portable-ascii/src/voku/helper/ASCII.php on line 795

### ISSUE THREAD

**Issue by prakhardubey2002** [voku/portable-ascii#106]
#### What is this feature about (expected vs actual behaviour)?
Dont know why this error was coming i just upgraded the PHP version from php-8.1.10-nts-Win32-vs17-x64  to php-8.4.0-nts-Win32-vs17-x64  in laragon due to composer.json's platform dependency check 
#### How can I reproduce it?
Simply Create a reactinertia-breeze app with laragon at php8.4 version 
#### Does it take minutes, hours or days to fix?
The error goes away when PHP version is downgraded to php-8.3.14-nts-Win32-vs17-x64
#### Any additional information?
![image](https://github.com/user-attachments/assets/beafd5a4-abb3-4e22-8a08-bba70a0ad75d)

**Comment by phildawson-gravity** [comment]
This was fixed in 2.0.2 so if you update it'll fix.

(If you explicitly passed null it'll break however due to it now expecting a bool only. See the 105 PR)

https://github.com/voku/portable-ascii/pull/105

**Comment by gilbertoalbino** [comment]
Hi, @prakhardubey2002. 
Hope you are fine! 
PHP 8.4 like every other previous versions has both deprecated or removed features, so you may not be able to run the project which previously you run with another PHP version.
In such cases, if you experience any error, just run `composer update `(not composer install) using your newest PHP version.
Don't ever do that on production before making sure your project runs on the newest PHP version.
Once everything is fine on development, on production, you just run `composer install` making sure you have the same PHP version.

**Comment by prakhardubey2002** [comment]
@gilbertoalbino  Ok Thanks
