### ISSUE TITLE
Is Croatian to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#11]
Example: Is this correct? 

"sveučilišt" -> "sveucilist"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L412

**Comment by ludifonovac** [comment]
This one is correct although there is another letter in Croatian language which is represented by two letters: dž->dz / Dž->Dz

**Comment by voku** [comment]
so this is correct? ->

```php
 // Croatian (Hrvatska)
    'hr' => [
        'dž' => 'dz',
        'Dž' => 'Dz',
        'ž' => 'z',
        'Ž' => 'Z',
        'đ' => 'dj',
        'Đ' => 'Dj',
        'č' => 'c',
        'Č' => 'C',
        'ć' => 'c',
        'Ć' => 'C',
        'š' => 's',
        'Š' => 'S',
    ],
```

**Comment by ludifonovac** [comment]
yes

**Comment by voku** [comment]
Thanks for the review. :1st_place_medal:
