### ISSUE TITLE
Is Finnish to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#12]
Example: Is this correct? 

"päiväkoti" -> "paivakoti"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L424

**Comment by hur** [comment]
It's not necessarily correct (will change the meaning of the word e.g. lähti vs lahti). The language should still be understandable in most cases ("paivakoti" looks like what you would write if you had no access to a finnish keyboard).

**Comment by voku** [comment]
Do you know a better way to convert Finnish text in ASCII?

**Comment by hur** [comment]
I think the current implementation is the best way.

**Comment by voku** [comment]
@hur Thanks for the re-view. :+1:
