### ISSUE TITLE
Is Czech to ASCII correct

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#16]
Example: Is this correct? 

"univerzitní" -> "univerzitni"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L567

**Comment by slepic** [comment]
The czech is incomplete
aáAÁ
cčCČ
dďDĎ
eéEÉ
eěEĚ
iíIÍ
nňNŇ
oóOÓ
rřRŘ
sšSŠ
tťTŤ
uúUÚ
uůUŮ
yýYÝ
zžZŽ

**Comment by voku** [comment]
@slepic thanks for the fix :+1:
