### ISSUE TITLE
Is Polish to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#18]
Example: Is this correct? 

"Odwiedzający" -> "Odwiedzajacy"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L600

**Comment by daryush** [comment]
Beside of this fix: https://github.com/voku/portable-ascii/pull/36 rest looks ok.

**Comment by voku** [comment]
Thank you for the review. :1st_place_medal:
