### ISSUE TITLE
Unrelsolved Bulgarian Ascii Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [voku/portable-ascii#2]
Input: `х Х щ Щ ъ Ъ ия йо`

Output: `h H sht Sht a A iya yo`

Expected output: `h H sht Sht a A ia yo`

**Comment by voku** [comment]
Thanks for the bug report. Fixed in version 1.2.3

**Comment by GrahamCampbell** [comment]
Thanks. One more thing. I'm just wondering if the `Щ` should be converted to entirely uppercase? Like A umlaut is?

**Comment by voku** [comment]
In german I would use upper+lower-case syntax e.g.: "Übung" -> "Uebung"

**Comment by GrahamCampbell** [comment]
What about writing a string that's entirely in upper case?
