### ISSUE TITLE
Is Lithuanian to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#23]
Example: Is this correct? 

"vaikų darželis" -> "vaiku darzelis"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L693

**Comment by Dohxis** [comment]
I am a native speaker and can confirm that the mapping is correct.

**Comment by voku** [comment]
Thanks for the confirmation.
