### ISSUE TITLE
Is Norwegian to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#24]
Example: Is this correct? 

"kundestøtte" -> "kundestoette"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L714

**Comment by Nyholm** [comment]
Im Swedish. The Norwegian looks alright for me. 

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L1458-L1464

**Comment by voku** [comment]
Thanks for the review. :+1:
