### ISSUE TITLE
Is Vietnamese to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#25]
Example: Is this correct? 

"trường học" -> "truong hoc"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L723

**Comment by cvhau** [comment]
I have checked, all special Vietnamese characters to ASCII mapping are correct.

**Comment by voku** [comment]
Thanks for checking it. :1st_place_medal:

**Comment by MinhQuan1909** [comment]
.
