### ISSUE TITLE
Is Serbian to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#28]
Example: Is this correct? 

"универзитет" -> "univerzitet"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L926

**Comment by ludifonovac** [comment]
Basically, you got it correctly. You used cyrilic scripture (which is default one for Serbian language) and added some letters in latin scripture (which is also widely used, and by law equal to cyrilic): 
'Đ' => 'Dj', 'Ð' => 'Dj', 'đ' => 'dj', 'š' => 's', 'ž' => 'z', 'ć' => 'c', 'č' => 'c', 'Š' => 'S', 'Ž' => 'Z', 'Ć' => 'C', 'Č' => 'C'
This one: 'ð' => 'dj'
is not used in Serbian language (in either scripture)

**Comment by voku** [comment]
so I can delete ```'ð' => 'dj'``` from the "sr" (Serbian) array and keep the ```'ð' => 'd'``` in the "latin" array?

PS: Is 'ð' not the lowercase symbol of 'Ð' in Serbian language?

**Comment by nikolaposa** [comment]
I've never encountered `ð` symbol, where did you find that one? Lowercase Serbian Latin `Ð` is `đ` while corresponding Serbian Cyrillic symbols are `Ђ` and `ђ`.

**Comment by ludifonovac** [comment]
ð is not the letter in Serbian language (not in cyrilic nor latin scripture)... It looks like a letter from Icelandic alphabet: https://en.wikipedia.org/wiki/Icelandic_orthography#/media/File:Latin_letter_%C3%90.svg

For latin scripture, you can use ones you used in Croatian

**Comment by voku** [comment]
@nikolaposa / @ludifonovac ... so I removed the ```ð``` char for Serbian language, do you think that the mapping is correct now?

**Comment by nikolaposa** [comment]
Yeah, I think I've noticed duplicated `Đ` (https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L1143-L1144), but apart from that it's good. 

Although it would be much easier to review and reason about mappings if they were sorted alphabetically, like so:

```
//Cyrillic
'а' => 'a',
'б' => 'b',
'в' => 'v',
'г' => 'g',
'д' => 'd',
'ђ' => 'dj',
'е' => 'e',
'ж' => 'z',
'з' => 'z',
'и' => 'i',
'ј' => 'j',
'к' => 'k',
'л' => 'l',
'љ' => 'lj',
'м' => 'm',
'н' => 'n',
'њ' => 'nj',
'о' => 'o',
'п' => 'p',
'р' => 'r',
'с' => 's',
'т' => 't',
'ћ' => 'c',
'у' => 'u',
'ф' => 'f',
'х' => 'h',
'ц' => 'c',
'ч' => 'c',
'џ' => 'dz',
'ш' => 's',
'А' => 'A',
'Б' => 'B',
'В' => 'V',
'Г' => 'G',
'Д' => 'D',
'Ђ' => 'Dj',
'Е' => 'E',
'Ж' => 'Z',
'З' => 'Z',
'И' => 'I',
'Ј' => 'j',
'К' => 'K',
'Л' => 'L',
'Љ' => 'Lj',
'М' => 'M',
'Н' => 'N',
'Њ' => 'Nj',
'О' => 'O',
'П' => 'P',
'Р' => 'R',
'С' => 'S',
'Т' => 'T',
'Ћ' => 'C',
'У' => 'U',
'Ф' => 'F',
'Х' => 'H',
'Ц' => 'C',
'Ч' => 'C',
'Џ' => 'Dz',
'Ш' => 'S',
//Latin
'đ' => 'dj',
'ž' => 'z',
'ć' => 'c',
'č' => 'c',
'š' => 's',
'Đ' => 'Dj',
'Ž' => 'Z',
'Ć' => 'C',
'Č' => 'C',
'Š' => 'S',
```

Also notice that I've grouped Cyrillic and Latin characters. That being said you can also consider having separate `sr_cyr` and `sr_lat` maps.
