### ISSUE TITLE
Is Russian to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#3]
Example: Is this correct? 

"лысая гора" -> "lysaja gora"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L468

**Comment by kalessil** [comment]
http://translit.cc/ for rescue, this specific case will be "lysaja gora".

**Comment by voku** [comment]
Thanks @kalessil I have merged the suggestions from "translit.ru" and "translit.cc" here: https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L468

**Comment by samdark** [comment]
There are multiple ways to tranlit and there are many GOSTs (state standards). Using the one for passports would produce "lysaia gora".

**Comment by samdark** [comment]
https://en.m.wikipedia.org/wiki/Romanization_of_Russian

**Comment by Hlaford** [comment]
> There are multiple ways to tranlit and there are many GOSTs (state standards). Using the one for passports would produce "lysaia gora".

I would use this one, actually. It is GOSTed (i.e. standardized).

**Comment by samdark** [comment]
@Hlaford the problem is that there are multiple standards that are not deprecated.

**Comment by GrahamCampbell** [comment]
Do different standards all have the same language code?

**Comment by samdark** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Hmm, I guess we just need to choose a standard.

**Comment by samdark** [comment]
No, that won't work well. If it's something like generating slugs for an article title, that doesn't matter much which standard is used. If it's passport names, your users may get in trouble if you aren't using correct standard. If your service if exchanging info with state road police, it matters to use correct standard for road signs and street names.

**Comment by samdark** [comment]
So solution would be allowing to choose a standard.

**Comment by kalessil** [comment]
+1 for "So solution would be allowing to choose a standard."

**Comment by voku** [comment]
@samdark Ok, so what standards do a normal application / user need? 

"Passport (2013)" + "GOST 7.79-2000(B)" -> https://en.m.wikipedia.org/wiki/Romanization_of_Russian#content-collapsible-block-1

**Comment by samdark** [comment]
Yes. Would be enough for many typical cases.

**Comment by voku** [comment]
@samdark I added mappings for "ru__passport_2013" && "ru__gost_2000_b" (copy&past from wikipedia). 

Can you please take a look at it, here is a test case for the string "лысая гора": https://github.com/voku/portable-ascii/commit/a2b1920093b2df9dbbb9334cdfa482c9f879f018

Mappings:
- Russian - Passport (2013), ICAO | https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L539
- Russian - GOST 7.79-2000(B) | https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L641

**Comment by samdark** [comment]
Looks OK to me.

**Comment by voku** [comment]
Thank you for the review & feedback. :+1:
