### ISSUE TITLE
Is Slovak to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#30]
Example: Is this correct? 

"zákazník" -> "zakaznik"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L1018

**Comment by mtnorthrop** [comment]
I'm not a native speaker, but I've lived in Slovakia for 15 years and speak the language and can confirm that the Slovak to ASCII is correct.

**Comment by voku** [comment]
Thank you for the review. :1st_place_medal:
