### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by staabm** [voku/portable-ascii#48]
The recent release growed in size by ~45000 lines because of https://github.com/voku/portable-ascii/commit/5417140259b3d2e9a8673908f61e55c4e1346e64

We bundle the lib with our cms and it makes a big portion of our overall application size, see https://github.com/redaxo/redaxo/pull/3662

Do you have any recommendations/suggestions on how we could save in filesize?
Maybe we can reduce the size of the data folder when we do some assumptions?

**Comment by voku** [comment]
Thanks for the hint. I have removed the new comments in these files, so that the file-size should be ~ as big as before.

**Comment by staabm** [comment]
for reference: fixed with https://github.com/voku/portable-ascii/commit/9ca15a8ddd61ad5857d5b71f5a0b991822c615e6
