### ISSUE TITLE
Some character mappings include a quote symbol

### ISSUE THREAD

**Issue by brandonkelly** [voku/portable-ascii#58]
Some ASCII character mappings include a quote symbol:

https://github.com/voku/portable-ascii/blob/0a05e9edb3b51f4a04ae9c2da7ba57b091200610/src/voku/helper/data/ascii_by_languages.php#L1224-L1225

https://github.com/voku/portable-ascii/blob/0a05e9edb3b51f4a04ae9c2da7ba57b091200610/src/voku/helper/data/ascii_by_languages.php#L1228-L1229

Were these intended?

**Comment by voku** [comment]
By default, we now prefer "Russian - Passport (2013), ICAO" instead of "Russian - GOST 7.79-2000(B)" because native people confirm that this should be the default. But some ASCII mappings (also the native PHP functions) contains quote symbols.

**Comment by staabm** [comment]
> But some ASCII mappings (also the native PHP functions) contains quote symbols.

should this be reported to php-src?

**Comment by voku** [comment]
> > But some ASCII mappings (also the native PHP functions) contains quote symbols.
> 
> should this be reported to php-src?

I think it's ok because some mappings contains quotes, it's maybe not expected for us, but it seems to be correct.
