### ISSUE TITLE
Is Turkish to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#7]
Example: Is this correct? 

"görüşmek" -> "gorusmek"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L193

**Comment by omerkoseoglu** [comment]
Yes. It is correct.

**Comment by voku** [comment]
Thanks for the feedback! :+1:
