### ISSUE TITLE
Update v1.6.0 broke Laravel's builds

### ISSUE THREAD

**Issue by driesvints** [voku/portable-ascii#74]
#### What is this feature about (expected vs actual behaviour)?

Seems like release v1.6.0 broke Laravel's build and subsequently all PR's that are sent in since are failing as well: https://github.com/laravel/framework/runs/4920401730?check_suite_focus=true#step:8:138

It seems most likely that this commit is the culprit: https://github.com/voku/portable-ascii/commit/acaf86813ba78f0787bcf6294fc1b55c044ae7a5

Changing the behaviour here seems like a breaking change to me and should probably be done in a major release?

#### How can I reproduce it?

```php
voku\helper\ASCII::to_ascii('пиздюк.txt');
```

Expected output: `pizdyuk.txt` (pre 1.6.0)
Given output: `pizdiuk.txt` (as of 1.6.0)

#### Does it take minutes, hours or days to fix?

Think this is an easy fix by just rolling back the commit and tagging a new patch release.

**Comment by voku** [comment]
I am currently in the hospital (my little girl had her heart operation last week, everything went well 🙏) and I will take a look this evening.

"It's more a fix for the current behaviour for Russia ascii mappings, but I can re-tag with a major version anyway. Should I remove the old tag? 🤔" - https://twitter.com/suckup_de/status/1485641365233049605?t=ncRafqzpgbWbFXIiL2HFUw

**Comment by driesvints** [comment]
Ow man, don't worry about it at all. We already fixed it on our end by limiting the constraint to `<1.6.0`. This is in no way urgent 👍 

Hope your girl recovers soon! ❤️

**Comment by voku** [comment]
@driesvints I reverted the "ASCII"-mappings and tagged 1.6.1 and 2.0.0 https://github.com/voku/portable-ascii/compare/1.6.1...2.0.0

**Comment by driesvints** [comment]
@voku thanks a lot! 👏
