### ISSUE TITLE
Is Hungarian to ASCII correct? 

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#9]
Example: Is this correct? 

"vásárló" -> vasarlo"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L274

**Comment by 1ed** [comment]
Hi! It seems good to me.

**Comment by voku** [comment]
Thank you for the feedback. :+1:
